import { Subscriber } from './Subscriber';

/**
     * mock data
     */
export const MockSubscribers: Subscriber[] = [
    {
        key: '1',
        code: 'HCM1_00000001',
        name: 'Nguyễn Văn A',
        age: 32,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký từ Web',
    },
    {
        key: '2',
        code: 'HCM1_00000002',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N4',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '2',
        code: 'HCM1_00000002',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'Giao tiếp cơ bản',
        status: 'Đã đóng tiền',
    },
    {
        key: '3',
        code: 'HCM1_00000003',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đã làm hợp đồng',
    },
    {
        key: '4',
        code: 'HCM1_00000004',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Huỷ đăng ký',
    },
    {
        key: '5',
        code: 'HCM1_00000005',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '6',
        code: 'HCM1_00000006',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '7',
        code: 'HCM1_00000007',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '8',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '9',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '10',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '11',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '12',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '13',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '14',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '15',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '16',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '17',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '18',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '19',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
    {
        key: '20',
        code: 'HCM1_00000008',
        name: 'Nguyễn Thị B',
        age: 42,
        address: '10 Downing Street',
        tel: '0987654321',
        email: '',
        subject: 'N5',
        status: 'Đăng ký trực tiếp',
    },
]